### ISSUE TITLE
Pull Request Template Not Applying

### ISSUE THREAD

**Issue by proidiot** [stuphlabs/7l7w2020#6]
**Describe the bug**
Pull request template is not being applied when a new pull request is made.

**To Reproduce**
1. Create a new branch in whichever fork.
2. Create a pull request.
3. Observe that the pull request description box is empty.

**Expected behavior**
When a new pull request is created, the pull request description box is pre-populated with the pull request template.

**Screenshots**
![image](https://user-images.githubusercontent.com/905503/79062593-6e27de80-7c61-11ea-9aa5-6e1d186d49fa.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser Chrome
 - Version 81.0.4044.94 (Official Build) (64-bit)

**Additional context**
_None_

**Comment by geekthattweaks** [comment]
I'm not quite sure what is wrong here. Looked through the documentation and it looks like it is all set up correctly. Made a new pull request for testing.
